name: fAuth
main: pt.flawless.fAuth.FAuth
description: Server auth
version: 1.0
depend: [fAPI]
commands:
  login:
    description: Login into a player's account
    aliases:
      - logar
  register:
    description: Register a player's account
    aliases:
      - registar
